### ISSUE TITLE
v3 class might be easier to follow if Flow were introduced after completing the react app.

### ISSUE THREAD

**Issue by evgenyfadeev** [btholt/complete-intro-to-react#106]
Sorry I couldn't find other way to give feedback (is there some other place on the Front End Masters or the feedback can be given here?)

Once flow was added to the class, for me it became more difficult to learn react itself.
Perhaps it would be better to complete all the coding parts and then add the flow, in order to untangle the learning tasks.

I liked the way flow annotations were added after applying redux later in the course.

I'll add one more feedback on the FM class - at some point in the videos you've stopped mentioning which git branch to check out and it became harder to keep the code in sync with the video lectures.

Thank you!

**Comment by btholt** [comment]
v4 isn't going to have type checking. :)
