### ISSUE TITLE
React Router route properties

### ISSUE THREAD

**Issue by ryanyogan** [btholt/complete-intro-to-react#11]
Now that this is on FEM's site, some individuals are most likely going to hit an issue with passing props via a route component, up until you switch to Redux: 

https://github.com/btholt/complete-intro-to-react/blob/fem-final/js/Search.jsx#L17

You will want to access them via `this.props.route.shows` as `this.props.shows` will give an undefined and filter will fail.

**Comment by btholt** [comment]
Yeah, definitely need to fix that. I'm abroad currently but if you make a PR I can merge it. Otherwise I'll do it when I get back.

**Comment by ryanyogan** [comment]
I'll make a PR with a few changes tomorrow, nice course man, glad you hit on chunking. That sounds funny if you don't use webpack.

**Comment by btholt** [comment]
Just merged #16! 🔥 🔥 🔥
