### ISSUE TITLE
start branch

### ISSUE THREAD

**Issue by skbolton** [btholt/complete-intro-to-react#12]
When it gets to the webpack section of the course I ran into some problems. I couldn't see the bundle.js output. After some digging I found that you have public/bundle.js hidden through .gitignore. Maybe this is explained later on in the course why you hide it but it definitely gave me some problems.

**Comment by thiagodebastos** [comment]
@skbolton Hi there! `bundle.js` should always be ignored, as with any build outputs. You don't want build outputs polluting your commit history.

If you do commit `bundle.js` you would double the changes committed every time (in the source file and the output bundled file).

If you have used CSS pre-processors. It's like ignoring the `.css` output of your `.scss` files.

I hope that helps!

**Comment by skbolton** [comment]
Yeah that makes sense. I was only complaining because in the course he clicks open the bundle.js for people to look at. I then realized my editor has a feature that hides VCS ignored files so I couldn't find it. More of an edge case that affected me. Thanks for the response, I will close this issue.

**Comment by thiagodebastos** [comment]
Ah makes sense now! That's funny I've gone through the exact issue myself in the past. It's these little issues that usually make no sense initially that kill us hehe. All the best!
