### ISSUE TITLE
getComponent param is not error, but __webpack.require__()

### ISSUE THREAD

**Issue by ZachStoltz** [btholt/complete-intro-to-react#13]
On a fresh clone and running off the master branch I get the following error on each route. It causes the Search to not render when navigated to.
[
<img width="487" alt="screen shot 2016-08-19 at 11 47 50 am" src="https://cloud.githubusercontent.com/assets/3913681/17815686/6c5e113c-6603-11e6-859d-b7b47b4c84a7.png">
](url)

**Comment by btholt** [comment]
Good catch. I'm on vacation right now but if you make a PR I can merge it. Otherwise I'll fix it in a few weeks.

**Comment by ZachStoltz** [comment]
No worries @btholt.  I can have a PR ready this afternoon.  Enjoy vacation!!

**Comment by ubatin** [comment]
I'm have the same issue. How can I fixed.

**Comment by btholt** [comment]
Resolved with 828d8c2403655d9c6be252eeeb015cf374de8568
