### ISSUE TITLE
Awesome tutorial, thanks!

### ISSUE THREAD

**Issue by therayess** [btholt/complete-intro-to-react#25]
Wanted to thank you for this amazing write up and intro to react/redux, one of the best tutorials i had to search the net for to learn react, well done 👍 

I have one question please, i'm pretty much using all you've taught in this tutorial and now have got a react/redux universal app running, but i just wanted to ask you, how did you deal with the absolute url's issue that occurs all the time when rendering on server?

**Comment by btholt** [comment]
I'm reworking the tutorial so when I get there I'll let you know (I don't remember!)

**Comment by francisngo** [comment]
I like to add that this was a wonderful tutorial. I learned a lot. I am reviewing the first version and am about to start version 2 to see all the new features. I was wondering, do we ever learn how to deploy the code onto heroku? I am trying to do it and am running into issues.

**Comment by btholt** [comment]
I do appreciate the kind words. I have little experience with Heroku, sorry! I don't have any meaningful experience to share.
