### ISSUE TITLE
No index.html file in Start Branch

### ISSUE THREAD

**Issue by bkilrain** [btholt/complete-intro-to-react#36]
I just started the frontend masters course and right off the bat, you direct us to open index.html in the 'start' branch. But in that particular branch... that file doesn't exist. Just letting ya know~

**Comment by ivannieto** [comment]
@bkilrain if I'm not wrong, it's supposed to be one of the first practices in the workshop. How to define your app into your index.html file. So, I guess this Issue could be closed.

**Comment by bkilrain** [comment]
You're  right... V1 of the talk used straight up boilerplate html. I just caught V2 and Brian actually walks through creating the index.html.

**Comment by mcqnyc** [comment]
@bkilrain I started the frontend masters course myself today and noticed the same thing as you did above. I have been looking for V2 of the workshop on frontend masters but can't find it. I just emailed support over there for a link and am also wondering if you could point me in the direction of where you were able to watch it?

**Comment by bkilrain** [comment]
@mcqnyc There is a section on FEM that is for live seminars. Within that section, you can see recent videos that were recorded but haven't yet been made into a proper course. You should be able to find it there.

**Comment by mcqnyc** [comment]
Thank you very much for getting back to me.  I will check out the live
section. Much appreciated!
