### ISSUE TITLE
Missing Curly Brace in html script tag within guide.

### ISSUE THREAD

**Issue by lordliquid** [btholt/complete-intro-to-react#42]
Following along the written tutorial ( active FrontEndMasters subscriber here. )
I have found a VERY MINOR ISSUE in the guide. Just thought I would help out for anyone still learning. The code displayed on the guide seems to be missing a curly brace. 

```
        var MyFirstComponent = React.createClass({
          render: function () {
            return (
              div(null,
                h1(null, 'This is my first component!')
              )
            )
          }
       }) // <-- Was Missing From Here

        ReactDOM.render(React.createElement(MyFirstComponent), document.getElementById('app'))

```

Just in case it helps solve any confusion.

So far, this course has been amazing! Thanks!

**Comment by btholt** [comment]
Should be resolved in v3.
