### ISSUE TITLE
SSR on v2-25 not working.

### ISSUE THREAD

**Issue by bmullican** [btholt/complete-intro-to-react#44]
Having an issue with SSR on v2-25. It worked on v2-23 when you did a view source, but not v2-25. Thoughts?

**Comment by gpspake** [comment]
I'm having the same issue. (I assume you just see a loading screen) 
In my case, it looks like the html is being written to bundle.js (weird)
Awesome course I just finished up but everything exploded as soon as we started setting up the ssr.
I suspect this might be related to globally installed node modules on my machine or something else local if it's working for other people. I tried uninstalling any globally installed node modules; is there something else I can try? Are there packages I need to have installed globally?

To reproduce:
```
git clone -b v2-25 git@github.com:btholt/complete-intro-to-react.git
cd complete-intro-to-react
yarn
npm start
```
in case it's important, yarn gripes a little
```
yarn install v0.18.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Incorrect peer dependency "react@^0.14.0".
warning Incorrect peer dependency "react@0.13.x || 0.14.x".
warning Incorrect peer dependency "enzyme@^2.4.1".
warning Incorrect peer dependency "eslint@>=1.6.0 <3.0.0".
warning Incorrect peer dependency "webpack@>=1.3.0 <3".
[4/4] 📃  Building fresh packages...
✨  Done in 9.46s.
```
bundle.js contains the following html 🤔 
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Frontend Masters React</title>
  <link rel="stylesheet" href="/public/normalize.css">
  <link rel="stylesheet" href="/public/style.css">
</head>
<body>
  <div id="app"><div class="app" data-reactroot="" data-reactid="1" data-react-checksum="561784551"><!-- react-empty: 2 --><!-- react-empty: 3 --><!-- react-empty: 4 --></div></div>
  <script src="/public/bundle.js"></script>
</body>
</html>
```
so the error in the browser is `Uncaught SyntaxError: Unexpected token <`

the dev server works fine on v-25 `npm run dev`

I can't get v-23 to work either if I follow the same steps as above, I get the following error
```
> complete-intro-to-react@1.0.0 start /Users/gpspake/development/test/complete-intro-to-react
> node server.js

/Users/gpspake/development/test/complete-intro-to-react/js/App.js:3
import React from 'react';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at loader (/Users/gpspake/development/test/complete-intro-to-react/node_modules/babel-register/lib/node.js:143:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gpspake/development/test/complete-intro-to-react/node_modules/babel-register/lib/node.js:153:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gpspake/development/test/complete-intro-to-react/server.js:13:13)
```
looks like node's getting to that import before babel or something

**Comment by richardjboothe** [comment]
SSR hasn't worked for me either. Though my error seems to be a webpack issue: `ClientApp.js:13 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_react_dom___default(...) is not a function
    at eval (ClientApp.js:13)
    at Object.<anonymous> (bundle.js:1979)
    at __webpack_require__ (bundle.js:48)
    at bundle.js:133
    at bundle.js:136`

**Comment by richardjboothe** [comment]
Resolved the issue. Try deleting all of your bundle.js files (there should be 1-3 of them depending on where you are in the SSR portion of the class) and rebuild your bundle.js files with: 
`npm run build` 
Hopefully that resolves your issues as well.

**Comment by bmullican** [comment]
No luck. I was pretty sure I had tried that before, but just to be sure I deleted all the bundle files and rebuilt them. Same result as before. The app works it's just not sending the html rendered on the server. If I view the page source all I get is:

<div id="app"><div class="app" data-reactroot="" data-reactid="1" data-react-checksum="2112891796"><h1 data-reactid="2">loading...</h1></div></div>

but on v2-23 I get:

<div id="app"><div class="app" data-reactroot="" data-reactid="1" data-react-checksum="2055040468"><div class="landing" data-reactid="2"><h1 data-reactid="3">svideo</h1><form data-reactid="4"><input type="text" value="" placeholder="Search" data-reactid="5"/></form><a href="/search" class="" data-reactid="6">or Browse All</a></div></div></div>

I'm sure there could many reasons for this. Is SSR working for you on v2-25 @richardjboothe?

**Comment by lehcosta** [comment]
@bmullican @richardjboothe  I have the same problem. Did you solve it?

**Comment by DiogenisPanagiotis** [comment]
@richardjboothe this worked great - thanks!

**Comment by btholt** [comment]
Should be addressed with v3. Thanks for helping each other out!
