### ISSUE TITLE
Missing 'npm install'

### ISSUE THREAD

**Issue by codazoda** [btholt/complete-intro-to-react#48]
Prior to the /My First Component/ section the document doesn't suggest `npm install`. It's probably a given for those with npm experience but might be worth mentioning for those who are not.

**Comment by nicknish** [comment]
Hey @codazoda, if you're referring to the most recent version (>v2) then this repo is setup to use yarn. Try `yarn`.

**Comment by codazoda** [comment]
@nicknish Yeah, I should have noticed that. Same difference though. The instructions don't tell you to run npm or yarn so that step should probably be added. @btholt has another react training repo. That one does have the yarn information and it might supersede this one; maybe.

**Comment by nicknish** [comment]
@codazoda Got it. Maybe the README could be a bit more fleshed out, however, if you follow the link in the README/headline to the repo's project page, you'll find it has all the walkthrough details you're looking for, including `yarn`. 

[https://btholt.github.io/complete-intro-to-react/all.html](https://btholt.github.io/complete-intro-to-react/all.html) (Setup section)

**Comment by codazoda** [comment]
Actually, I think I just missed the sentence that says to run "yarn" from the directory where you cloned the repo. The info is there, I just missed it somehow.

**Comment by btholt** [comment]
I'm reworking the workshop for v3 and I'll add a note to make sure people run yarn before running the app.
