### ISSUE TITLE
Everything works fine locally, but deploying to real NodeJS server didn't work out

### ISSUE THREAD

**Issue by Y-Taras** [btholt/complete-intro-to-react#50]
As I've already told, App is working absolutely as expected on my local machine without any errors.
I've registered an account on IBM Bluemix  for a trial. Then I pushed an app to the server and then It looks like it doesn't understand es6 in js/App.js.
![screenshot from 2017-03-01 13 32 30](https://cloud.githubusercontent.com/assets/8538134/23458174/bf57063c-fe83-11e6-9142-fb01c3c862b5.png)

**Comment by Y-Taras** [comment]
On Bluemix I couldn't properly change the NODE_ENV=server, so instead

1.  I changed in `.babelrc` file `env` to `production`
 2. In `packages.json` moved  packages from devdependencies to dependencies, that were in `.babelrc` presets and `babel-register`, that was required in `server.js` file: 

- "babel-loader":

-   "babel-preset-es2015"

-   "babel-plugin-transform-es2015-modules-commonjs"

-  "babel-register"

- "babel-preset-react"

3. Changed a port in server.js from 5050 to 8080 because it didn't work with 5050
That's it

**Comment by aishwaryr** [comment]
@Y-Taras can you please tell me how did you prepare the project to deploy. The build that we get in public folder (as Brian taught in the course) doesn't have any index.html , so I'm a little confused. Generally in create-react-app projects on doing build we get a public/dist folder that can be uploaded to hosting services. Also in this project after applying server-side rendering we have a server.js too, do we need to host the server and client seperately? How should I proceed if want this project online.

**Comment by Y-Taras** [comment]
@aishwaryr  If it would help, you can look at working example of the my project. Here's a link [](url)

**Comment by Y-Taras** [comment]
@aishwaryr  If it would help, you can look at working example of the my project. Here's a link https://gitlab.com/ytaras/harazd
