### ISSUE TITLE
CSS not loading on master among other issues

### ISSUE THREAD

**Issue by narmeen12** [btholt/complete-intro-to-react#54]
The tutorials start repo has a lot of stuff already predefined so following the video tutorial was not helpful. I had to undo a lot of predefined things in the repo so I could try and follow along with the tutorial.  I then tried to just follow the text tutorial which also had a lot of errors I could not get past without hours of debugging. I eventually gave up and decided to just examine the master branch since I only needed a refresher on react/redux. Sadly, even the master branch not loading because the css files cannot be found...

The tutorial is working and easy to follow up until the tooling portion then it more or less falls apart. I could not even get babel to work so es6 syntax was not even available. Wasted a lot of time here and I understand Brian must be really busy and unable to correct this but Frontend Masters should really remove this tutorial until these issues are resolved.

Recommend providing a start repo that has nothing but the required modules

**Comment by ddvorak** [comment]
Yo, I havent followed this at all been busy with student web, just updated today, new version works :)

**Comment by vinnyA3** [comment]
What problems did you run into exactly ( excluding the css not loading on master )?  I cloned the start branch of the repo and haven't run into any roadblocks so far ( I'm up to React routing ).

**Comment by btholt** [comment]
Should be resolved with v3.
