### ISSUE TITLE
React.createClass

### ISSUE THREAD

**Issue by mardisworld** [btholt/complete-intro-to-react#57]
React.createClass is no longer a thing. I'm having trouble getting this to work.
![react createclass](https://cloud.githubusercontent.com/assets/9426702/25053155/9569f826-2123-11e7-8425-2aafb4692d14.jpeg)

**Comment by mwtrager** [comment]
You can migrate to ES6 classes fairly easily:

For example with the App component:

````javascript
class App extends React.Component {
  render () {
    return (
      <Router>
        <div className='app'>
          <Route exact path='/' component={Landing} />
          <Route path='/profile' component={Profile} />
        </div>
      </Router>
    )
  }
}

render(<App />, document.getElementById('app'))
````

instead of
````javascript
const App = React.CreateClass({
  render () {
    return (
      <Router>
        <div className='app'>
          <Route exact path='/' component={Landing} />
          <Route path='/profile' component={Profile} />
        </div>
      </Router>
    )
  }
}

render(<App />, document.getElementById('app'))
````

Make sure to have that upper case C on React.Component.

Alternative is to use a stateless functional component which would look like

````javascript
const App = () => {
  render () {
    return (
      <Router>
        <div className='app'>
          <Route exact path='/' component={Landing} />
          <Route path='/profile' component={Profile} />
        </div>
      </Router>
    )
  }
}

render(<App />, document.getElementById('app'))
````

Make sure to use the package 'react-router-dom' if you are getting rendering issues when using 'react-router' ... they migrated to a more universal library to be useful for React Native, so we explicitly pull in the DOM functions with 'react-router-dom' I think?

**Comment by mardisworld** [comment]
Thank you for your quick response! I have:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Front End Masters React</title>
</head>
<body>
<div id="app">React has not yet rendered.</div>
<script src="node_modules/react/dist/react.js"></script>
<script src="node_modules/react-dom/dist/react-dom.js"></script>
<script>
var div=React.DOM.div;
var h1=React.DOM.h1;

var createReactClass=require('create-react-class');

var MyFirstComponent=createReactClass({
render: function () {
  return(
div(null,
 h1(null, 'This is my first component.')
)
  );
}
});

ReactDOM.render(React.createElement(MyFirstComponent),
document.getElementById('app'));
</script>
</body>
</html>

as per the tutorial. I will try to work with what you've given me here.

**Comment by btholt** [comment]
This is being refactored out for v3. Stay tuned.
